export const MESSAGE_TYPE = {
  PING_REQUEST: 'PING_REQUEST',
  PING_RESPONSE: 'PING_RESPONSE',
  CHAT_NEW_MESSAGE: 'CHAT_NEW_MESSAGE',
  CHAT_SEND_MESSAGE: 'CHAT_SEND_MESSAGE',
  CHAT_SET_USER: 'CHAT_SET_USER',
  CHAT_NEW_USER: 'CHAT_NEW_USER',
  CHAT_USER_LEFT: 'CHAT_USER_LEFT',
};